"""Initial migration lazy 2

Revision ID: 38108fcd8f3b
Revises: d7baf925ac41
Create Date: 2025-03-23 10:43:06.141341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38108fcd8f3b'
down_revision = 'd7baf925ac41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_title'))
        batch_op.drop_index(batch_op.f('ix_course_category_id'))

    # ### end Alembic commands ###
